sudo: required

language: csharp

dist: trusty  
env:  
  - CLI_VERSION=latest
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - sshpass
 ssh_known_hosts:
  - 159.203.33.172

mono:  
  - 4.2.3
os:  
  - linux
  - osx
osx_image: xcode7.1  

branches:
  only:
  - master

addons:
  ssh_known_hosts:
  - 159.203.33.172
  apt:
    packages:
    - sshpass

cache:
  directories:
  - $HOME/packages

services:
  - docker

script:
  - export TRAVIS_BUILD_DIRECTORY=$PWD
  - docker build -t webapp:test -f dockerfiles/test .
  - docker run -it -v $HOME/packages:/root/.nuget/packages -v $PWD/publish:/root/publish webapp:test

after_success:
  - cd $TRAVIS_BUILD_DIRECTORY
  - docker build -t xaviercl/webapp:latest -f dockerfiles/release .
  - docker login -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD"
  - docker push xaviercl/webapp:latest
  - export SSHPASS=$TEST_SERVER_SSH_PASSWORD
  - sshpass -e scp -o StrictHostKeyChecking=no $PWD/scripts/releaseTestServer.sh u1440721@159.203.33.172:/home/u1440721
  - sshpass -e ssh u1440721@159.203.33.172 'chmod +x releaseTestServer.sh'
  - sshpass -e ssh u1440721@159.203.33.172 'sh releaseTestServer.sh'